export const CAT_BREEDS: string[] = [
  'Domestic Shorthair', 'Domestic Longhair', 'Siamese', 'Maine Coon',
  'Persian', 'British Shorthair', 'Ragdoll', 'Bengal', 'Sphynx',
  'Tabby', 'Mixed Breed', 'Other',
]

export const BREEDS: string[] = [
  'Labrador Retriever',
  'Golden Retriever',
  'German Shepherd',
  'French Bulldog',
  'Bulldog',
  'Poodle',
  'Beagle',
  'Rottweiler',
  'Yorkshire Terrier',
  'Dachshund',
  'Siberian Husky',
  'Boxer',
  'Shih Tzu',
  'Chihuahua',
  'Doberman Pinscher',
  'Australian Shepherd',
  'Border Collie',
  'Cavalier King Charles Spaniel',
  'Maltese',
  'Pomeranian',
  'Bichon Frise',
  'Cocker Spaniel',
  'Mixed Breed',
  'Other',
]
